@startuml
' declate title
title 2.3.0. Transfer Timeout

autonumber

' Actor Keys:
'   boundary - APIs/Interfaces, etc
'   collections - Kafka Topics
'   control - Kafka Consumers
'   entity - Database Access Objects
'   database - Database Persistance Store

' declare actors
actor "DFSP1\nPayer" as DFSP1
actor "DFSP2\nPayee" as DFSP2
boundary "ML API Adapter" as MLAPI
control "ML API Notification Event Handler" as NOTIFY_HANDLER
control "Transfer Timeout Handler" as EXP_HANDLER
collections "Topic-{currency}-DFSPn-Position-Abort" as TOPIC_POSITION_DFSP
control "Position Event Handler" as POS_HANDLER
collections "Transfer-Topic" as TOPIC_TRANSFERS
control "Transfer Event Handler" as TRANS_HANDLER
collections "Notification-Topic" as TOPIC_NOTIFICATIONS
collections "Event-Topic" as TOPIC_EVENT

box "Financial Service Providers" #lightGray
	participant DFSP1
	participant DFSP2
end box

box "ML API Adapter Service" #LightBlue
	participant MLAPI
	participant NOTIFY_HANDLER
end box

box "Central Service" #LightYellow
    participant EXP_HANDLER
    participant TOPIC_POSITION_DFSP
    participant TOPIC_EVENT
    participant POS_HANDLER
    participant TOPIC_TRANSFERS
    participant TRANS_HANDLER
    participant TOPIC_NOTIFICATIONS
end box

' start flow
activate NOTIFY_HANDLER
activate EXP_HANDLER
activate POS_HANDLER
activate TRANS_HANDLER
group Transfer Expiry
    |||
    ref over EXP_HANDLER, TOPIC_EVENT :  Timeout Handler Consume {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-timeout-2.3.1.svg 2.3.1.]]} \n
    alt transferStateId == 'RECEIVED_PREPARE'
        EXP_HANDLER -> TOPIC_NOTIFICATIONS: Produce message
    else transferStateId == 'RESERVED'
        EXP_HANDLER -> TOPIC_POSITION_DFSP: Produce message
        TOPIC_POSITION_DFSP <- POS_HANDLER: Consume message
        ref over TOPIC_POSITION_DFSP, TOPIC_TRANSFERS :  Position Hander Consume (Timeout) {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-position-1.3.3-abort.svg seq-position-1.3.3-abort.svg]]} \n
        POS_HANDLER -> TOPIC_TRANSFERS: Produce message
        |||
        TOPIC_TRANSFERS <- TRANS_HANDLER: Consume message
        ref over TOPIC_EVENT, TOPIC_NOTIFICATIONS : Transfer Handler Consume (Timeout) {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-timeout-2.3.3.svg 2.3.3.]]} \n
        TRANS_HANDLER -> TOPIC_NOTIFICATIONS: Produce message
    end
    TOPIC_NOTIFICATIONS <- NOTIFY_HANDLER: Consume message
    opt action IN ['timeout-received', 'timeout-reserved']
        |||
        ref over DFSP1, TOPIC_NOTIFICATIONS : Send notification to Participant (Payer) {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.4.a.svg 1.1.4.a.]]} \n
        NOTIFY_HANDLER -> DFSP1: Send callback notification
    end
    |||
    TOPIC_NOTIFICATIONS <- NOTIFY_HANDLER: Consume message
    opt action == 'timeout-reserved'
        |||
        ref over DFSP2, TOPIC_NOTIFICATIONS : Send notification to Participant (Payee) {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.4.a.svg 1.1.4.a.]]} \n
        NOTIFY_HANDLER -> DFSP2: Send callback notification
    end
end
deactivate TRANS_HANDLER
deactivate POS_HANDLER
deactivate EXP_HANDLER
deactivate NOTIFY_HANDLER
@enduml
