@startuml
' declate title
title 2.2.2. Position Handler Consume (Reject)

autonumber

' Actor Keys:
'   boundary - APIs/Interfaces, etc
'   collections - Kafka Topics
'   control - Kafka Consumers
'   entity - Database Access Objects
'   database - Database Persistance Store

' declare actors
collections "Position-Topic-dfsp1" as TOPIC_POSITION_DFSP1
control "Position Event Handler" as POS_HANDLER
collections "Transfer-Topic" as TOPIC_TRANSFERS
collections "Event-Topic" as TOPIC_EVENT
entity "Transfer DAO" as TRANS_DAO
entity "Position DAO" as POS_DAO
database "Central Store" as DB

box "Central Service" #LightYellow
    participant TOPIC_POSITION_DFSP1
    participant TOPIC_EVENT
    participant POS_HANDLER
    participant TOPIC_TRANSFERS
    participant TRANS_DAO
    participant POS_DAO
    participant DB
end box

' start flow
activate POS_HANDLER
group Position Handler Consume (Reject)
    alt Consume Single Message
        TOPIC_POSITION_DFSP1 <- POS_HANDLER: Consume Position event message for Payer
        activate TOPIC_POSITION_DFSP1
        deactivate TOPIC_POSITION_DFSP1

        break
            group Validate Event
                POS_HANDLER <-> POS_HANDLER: Validate event - Rule: type == 'position' && action == 'reject'
            end
        end

        group Persist Event Information
            POS_HANDLER -> TOPIC_EVENT: Publish event information
	        ref over POS_HANDLER, TOPIC_EVENT :  Event Handler Consume {[[https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-event-9.1.0.svg 9.1.0.]]} 
        end

        group Retrieve Current Transfer Details
            POS_HANDLER -> TRANS_DAO: Request to retrieve expirationDate & transferStateId
            activate TRANS_DAO
            TRANS_DAO -> DB: Fetch from database
            activate DB
            DB --> TRANS_DAO
            deactivate DB
            hnote over DB #lightyellow
                transfer
                transferState
            end note
            POS_HANDLER <-- TRANS_DAO: Return transfer.expirationDate & transferState.transferStateId
            deactivate TRANS_DAO
        end

        break
            group Validate Transfer
                POS_HANDLER <-> POS_HANDLER: Validate transfer expiration - Rule: Date.now() < expirationDate
                POS_HANDLER <-> POS_HANDLER: Validate transfer state - Rule: **transferState**Id corresponds to 'RESERVED'
            end
        end

        group Decrement Payer Position (DFSP1)
            POS_HANDLER -> POS_DAO: Request to decrement latest position for Payer
            activate POS_DAO
            POS_DAO -> DB: Persist decrement to DB
            activate DB
            deactivate DB
            hnote over DB #lightyellow
                transferPosition
            end note
            POS_DAO --> POS_HANDLER: Return success
            deactivate POS_DAO
        end

        group Persist Transfer State (with transferState='ABORTED')
            POS_HANDLER -> TRANS_DAO: Request to persist transfer state
            activate TRANS_DAO
            TRANS_DAO -> DB: Persist transfer state
            activate DB
            deactivate DB
            hnote over DB #lightyellow
                transferStateChange
            end note
            TRANS_DAO --> POS_HANDLER: Return success
            deactivate TRANS_DAO
        end
    
        note right of POS_HANDLER #yellow
            Message:
            {
                id: <ID>,
                from: <transferHeaders.FSPIOP-Source>,
                to: <transferHeaders.FSPIOP-Destination>,
                type: application/json,
                content: {
                    headers: <transferHeaders>,
                    payload: <transferMessage>
                },
                metadata: {
                    event: {
                        id: <uuid>,
                        responseTo: <previous.uuid>,
                        type: transfer,
                        action: reject,
                        createdAt: <timestamp>,
                        state: {
                            status: "success",
                            code: 0
                        }
                    }
                }
            }
        end note
        POS_HANDLER -> TOPIC_TRANSFERS: Publish Transfer event
        activate TOPIC_TRANSFERS
        deactivate TOPIC_TRANSFERS

    else Consume Batch Messages
        note left of POS_HANDLER #lightblue
            To be delivered by future story
        end note
    end
end
deactivate POS_HANDLER
@enduml
